-- AlterTable
ALTER TABLE "Board" ADD COLUMN "widthScale" DOUBLE PRECISION DEFAULT 1.0;
ALTER TABLE "Board" ADD COLUMN "bgPaddingX" INTEGER DEFAULT 0;
ALTER TABLE "Board" ADD COLUMN "bgPaddingY" INTEGER DEFAULT 0;
