-- AlterTable
ALTER TABLE "Board"
    ALTER COLUMN "bgX" TYPE DOUBLE PRECISION USING "bgX"::DOUBLE PRECISION,
    ALTER COLUMN "bgY" TYPE DOUBLE PRECISION USING "bgY"::DOUBLE PRECISION,
    ALTER COLUMN "bgPaddingX" TYPE DOUBLE PRECISION USING "bgPaddingX"::DOUBLE PRECISION,
    ALTER COLUMN "bgPaddingY" TYPE DOUBLE PRECISION USING "bgPaddingY"::DOUBLE PRECISION,
    ALTER COLUMN "gridOffsetX" TYPE DOUBLE PRECISION USING "gridOffsetX"::DOUBLE PRECISION,
    ALTER COLUMN "gridOffsetY" TYPE DOUBLE PRECISION USING "gridOffsetY"::DOUBLE PRECISION;
